### ISSUE TITLE
sql跪求大佬

### ISSUE THREAD

**Issue by arraycto** [CNwalking/MeetingRoom#4]
启动的时候，无法自动生成表额。求sql

**Comment by CNwalking** [comment]
加在readme上了

**Comment by CNwalking** [comment]
建表sql加载readme上了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CNwalking/MeetingRoom"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 下午2:59
收件人:&nbsp;"CNwalking/MeetingRoom"<MeetingRoom@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[CNwalking/MeetingRoom] sql跪求大佬 (#4)





 
启动的时候，无法自动生成表额。求sql

**Comment by arraycto** [comment]
非常好
