### ISSUE TITLE
请教一下，dao之类那些文件是用插件生成的吗，求推荐

### ISSUE THREAD

**Issue by OrangeHao** [CNwalking/MeetingRoom#5]
如题

**Comment by CNwalking** [comment]
见我写的另一个项目BaseProject 这里面的  BaseProject/src/test/java/CodeGenerator.java 这个test类，改下数据库连接和库名字，就能自动生成了，生成完以后挑一部分文件塞到你项目相应的地方。你也可以直接拷贝这个类和模板到你项目那里，然后修改模板和生成的位置。
